### ISSUE TITLE
Allow Hastebin host to be set in settings

### ISSUE THREAD

**Issue by dainman** [HamzaAnis/vscode-to-hastebin#2]
Would like to be able to set a variable in the settings file to use an internal hastebin server instead of the public hastebin.com

**Comment by HamzaAnis** [comment]
Yes this would be a good option and I will soon add this in the next version.

**Comment by wopol** [comment]
Please consider the merge this PR: https://github.com/HamzaAnis/vscode-to-hastebin/pull/3

**Comment by HamzaAnis** [comment]
@wopol Thank you very much for this PR. I'll test it and will merge it soon.

**Comment by HamzaAnis** [comment]
This feature has been added in the version [0.1.0](https://github.com/HamzaAnis/vscode-to-hastebin/releases/tag/0.1.0). Thanks for your recommendation.
